[package]
name = "cockpit-pacman-backend"
version = "0.2.0"
edition = "2021"

[features]
integration-tests = []

[dependencies]
alpm = "5"
alpm-utils = "5"
pacmanconf = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
ctrlc = "3"
pacman-key = "0.1.0"
pacman-log = "0.1"
tokio = { version = "1", features = ["rt-multi-thread"] }

[profile.release]
lto = true
strip = true
