[package]
name = "cockpit-pacman-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
alpm = "4"
alpm-utils = "4"
pacmanconf = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"

[profile.release]
lto = true
strip = true
